--- 
engines: 
  csslint: 
    enabled: true
  duplication: 
    config: 
      languages: 
        - 
          mass_threshold: 30
          ruby: ~
        - javascript
    enabled: true
  eslint: 
    enabled: true
  golint: 
    enabled: true
  rubocop: 
    enabled: true
exclude_paths: 
  - web-app/spec/**/*
  - "**/vendor/**/*"
  - web-app/assets/javascripts/graphs/
ratings: 
  paths: 
    - web-app/app/**
    - web-app/lib/**
    - "**.rb"